package com.shopizzo.ui.screens

data class CountryInfo(
    val name: String,
    val code: String,
    val flag: String
)

val shopizzoCountriesList = listOf(
    CountryInfo("Afghanistan", "+93", "🇦🇫"),
    CountryInfo("Albania", "+355", "🇦🇱"),
    CountryInfo("Algeria", "+213", "🇩🇿"),
    CountryInfo("Andorra", "+376", "🇦🇩"),
    CountryInfo("Angola", "+244", "🇦🇴"),
    CountryInfo("Argentina", "+54", "🇦🇷"),
    CountryInfo("Armenia", "+374", "🇦🇲"),
    CountryInfo("Australia", "+61", "🇦🇺"),
    CountryInfo("Azerbaijan", "+994", "🇦🇿"),
    CountryInfo("Bahamas", "+1-242", "🇧🇸"),
    CountryInfo("Bahrain", "+973", "🇧🇭"),
    CountryInfo("Bangladesh", "+880", "🇧🇩"),
    CountryInfo("Barbados", "+1-246", "🇧🇧"),
    CountryInfo("Belarus", "+375", "🇧🇾"),
    CountryInfo("Belgium", "+32", "🇧🇪"),
    CountryInfo("Belize", "+501", "🇧🇿"),
    CountryInfo("Benin", "+229", "🇧🇯"),
    CountryInfo("Bhutan", "+975", "🇧🇹"),
    CountryInfo("Bolivia", "+591", "🇧🇴"),
    CountryInfo("Bosnia and Herzegovina", "+387", "🇧🇦"),
    CountryInfo("Botswana", "+267", "🇧🇼"),
    CountryInfo("Brazil", "+55", "🇧🇷"),
    CountryInfo("Brunei", "+673", "🇧🇳"),
    CountryInfo("Bulgaria", "+359", "🇧🇬"),
    CountryInfo("Burkina Faso", "+226", "🇧🇫"),
    CountryInfo("Burundi", "+257", "🇧🇮"),
    CountryInfo("Cambodia", "+855", "🇰🇭"),
    CountryInfo("Cameroon", "+237", "🇨🇲"),
    CountryInfo("Canada", "+1", "🇨🇦"),
    CountryInfo("Cape Verde", "+238", "🇨🇻"),
    CountryInfo("Central African Republic", "+236", "🇨🇫"),
    CountryInfo("Chad", "+235", "🇹🇩"),
    CountryInfo("Chile", "+56", "🇨🇱"),
    CountryInfo("China", "+86", "🇨🇳"),
    CountryInfo("Colombia", "+57", "🇨🇴"),
    CountryInfo("Comoros", "+269", "🇰🇲"),
    CountryInfo("Congo", "+242", "🇨🇬"),
    CountryInfo("Costa Rica", "+506", "🇨🇷"),
    CountryInfo("Croatia", "+385", "🇭🇷"),
    CountryInfo("Cuba", "+53", "🇨🇺"),
    CountryInfo("Cyprus", "+357", "🇨🇾"),
    CountryInfo("Czech Republic", "+420", "🇨🇿"),
    CountryInfo("Denmark", "+45", "🇩🇰"),
    CountryInfo("Djibouti", "+253", "🇩🇯"),
    CountryInfo("Dominica", "+1-767", "🇩🇲"),
    CountryInfo("Dominican Republic", "+1-809", "🇩🇴"),
    CountryInfo("Ecuador", "+593", "🇪🇨"),
    CountryInfo("Egypt", "+20", "🇪🇬"),
    CountryInfo("El Salvador", "+503", "🇸🇻"),
    CountryInfo("Equatorial Guinea", "+240", "🇬🇶"),
    CountryInfo("Eritrea", "+291", "🇪🇷"),
    CountryInfo("Estonia", "+372", "🇪🇪"),
    CountryInfo("Ethiopia", "+251", "🇪🇹"),
    CountryInfo("Fiji", "+679", "🇫🇯"),
    CountryInfo("Finland", "+358", "🇫🇮"),
    CountryInfo("France", "+33", "🇫🇷"),
    CountryInfo("Gabon", "+241", "🇬🇦"),
    CountryInfo("Gambia", "+220", "🇬🇲"),
    CountryInfo("Georgia", "+995", "🇬🇪"),
    CountryInfo("Germany", "+49", "🇩🇪"),
    CountryInfo("Ghana", "+233", "🇬🇭"),
    CountryInfo("Greece", "+30", "🇬🇷"),
    CountryInfo("Grenada", "+1-473", "🇬🇩"),
    CountryInfo("Guatemala", "+502", "🇬🇹"),
    CountryInfo("Guinea", "+224", "🇬🇳"),
    CountryInfo("Guinea-Bissau", "+245", "🇬🇼"),
    CountryInfo("Guyana", "+592", "🇬🇾"),
    CountryInfo("Haiti", "+509", "🇭🇹"),
    CountryInfo("Honduras", "+504", "🇭🇳"),
    CountryInfo("Hungary", "+36", "🇭🇺"),
    CountryInfo("Iceland", "+354", "🇮🇸"),
    CountryInfo("India", "+91", "🇮🇳"),
    CountryInfo("Indonesia", "+62", "🇮🇩"),
    CountryInfo("Iran", "+98", "🇮🇷"),
    CountryInfo("Iraq", "+964", "🇮🇶"),
    CountryInfo("Ireland", "+353", "🇮🇪"),
    CountryInfo("Israel", "+972", "🇮🇱"),
    CountryInfo("Italy", "+39", "🇮🇹"),
    CountryInfo("Jamaica", "+1-876", "🇯🇲"),
    CountryInfo("Japan", "+81", "🇯🇵"),
    CountryInfo("Jordan", "+962", "🇯🇴"),
    CountryInfo("Kazakhstan", "+7", "🇰🇿"),
    CountryInfo("Kenya", "+254", "🇰🇪"),
    CountryInfo("Kuwait", "+965", "🇰🇼"),
    CountryInfo("Kyrgyzstan", "+996", "🇰🇬"),
    CountryInfo("Laos", "+856", "🇱🇦"),
    CountryInfo("Latvia", "+371", "🇱🇻"),
    CountryInfo("Lebanon", "+961", "🇱🇧"),
    CountryInfo("Lesotho", "+266", "🇱🇸"),
    CountryInfo("Liberia", "+231", "🇱🇷"),
    CountryInfo("Libya", "+218", "🇱🇾"),
    CountryInfo("Liechtenstein", "+423", "🇱🇮"),
    CountryInfo("Lithuania", "+370", "🇱🇹"),
    CountryInfo("Luxembourg", "+352", "🇱🇺"),
    CountryInfo("Madagascar", "+261", "🇲🇬"),
    CountryInfo("Malawi", "+265", "🇲🇼"),
    CountryInfo("Malaysia", "+60", "🇲🇾"),
    CountryInfo("Maldives", "+960", "🇲🇻"),
    CountryInfo("Mali", "+223", "🇲🇱"),
    CountryInfo("Malta", "+356", "🇲🇹"),
    CountryInfo("Mauritania", "+222", "🇲🇷"),
    CountryInfo("Mauritius", "+230", "🇲🇺"),
    CountryInfo("Mexico", "+52", "🇲🇽"),
    CountryInfo("Moldova", "+373", "🇲🇩"),
    CountryInfo("Monaco", "+377", "🇲🇨"),
    CountryInfo("Mongolia", "+976", "🇲🇳"),
    CountryInfo("Montenegro", "+382", "🇲🇪"),
    CountryInfo("Morocco", "+212", "🇲🇦"),
    CountryInfo("Mozambique", "+258", "🇲🇿"),
    CountryInfo("Myanmar", "+95", "🇲🇲"),
    CountryInfo("Namibia", "+264", "🇳🇦"),
    CountryInfo("Nepal", "+977", "🇳🇵"),
    CountryInfo("Netherlands", "+31", "🇳🇱"),
    CountryInfo("New Zealand", "+64", "🇳🇿"),
    CountryInfo("Nicaragua", "+505", "🇳🇮"),
    CountryInfo("Niger", "+227", "🇳🇪"),
    CountryInfo("Nigeria", "+234", "🇳🇬"),
    CountryInfo("Norway", "+47", "🇳🇴"),
    CountryInfo("Oman", "+968", "🇴🇲"),
    CountryInfo("Pakistan", "+92", "🇵🇰"),
    CountryInfo("Palestine", "+970", "🇵🇸"),
    CountryInfo("Panama", "+507", "🇵🇦"),
    CountryInfo("Papua New Guinea", "+675", "🇵🇬"),
    CountryInfo("Paraguay", "+595", "🇵🇾"),
    CountryInfo("Peru", "+51", "🇵🇪"),
    CountryInfo("Philippines", "+63", "🇵🇭"),
    CountryInfo("Poland", "+48", "🇵🇱"),
    CountryInfo("Portugal", "+351", "🇵🇹"),
    CountryInfo("Qatar", "+974", "🇶🇦"),
    CountryInfo("Romania", "+40", "🇷🇴"),
    CountryInfo("Russia", "+7", "🇷🇺"),
    CountryInfo("Rwanda", "+250", "🇷🇼"),
    CountryInfo("Saudi Arabia", "+966", "🇸🇦"),
    CountryInfo("Senegal", "+221", "🇸🇳"),
    CountryInfo("Serbia", "+381", "🇷🇸"),
    CountryInfo("Seychelles", "+248", "🇸🇨"),
    CountryInfo("Sierra Leone", "+232", "🇸🇱"),
    CountryInfo("Singapore", "+65", "🇸🇬"),
    CountryInfo("Slovakia", "+421", "🇸🇰"),
    CountryInfo("Slovenia", "+386", "🇸🇮"),
    CountryInfo("Somalia", "+252", "🇸🇴"),
    CountryInfo("South Africa", "+27", "🇿🇦"),
    CountryInfo("South Korea", "+82", "🇰🇷"),
    CountryInfo("South Sudan", "+211", "🇸🇸"),
    CountryInfo("Spain", "+34", "🇪🇸"),
    CountryInfo("Sri Lanka", "+94", "🇱🇰"),
    CountryInfo("Sudan", "+249", "🇸🇩"),
    CountryInfo("Suriname", "+597", "🇸🇷"),
    CountryInfo("Swaziland", "+268", "🇸🇿"),
    CountryInfo("Sweden", "+46", "🇸🇪"),
    CountryInfo("Switzerland", "+41", "🇨🇭"),
    CountryInfo("Syria", "+963", "🇸🇾"),
    CountryInfo("Taiwan", "+886", "🇹🇼"),
    CountryInfo("Tajikistan", "+992", "🇹🇯"),
    CountryInfo("Tanzania", "+255", "🇹🇿"),
    CountryInfo("Thailand", "+66", "🇹🇭"),
    CountryInfo("Togo", "+228", "🇹🇬"),
    CountryInfo("Tonga", "+676", "🇹🇴"),
    CountryInfo("Trinidad and Tobago", "+1-868", "🇹🇹"),
    CountryInfo("Tunisia", "+216", "🇹🇳"),
    CountryInfo("Turkey", "+90", "🇹🇷"),
    CountryInfo("Turkmenistan", "+993", "🇹🇲"),
    CountryInfo("Uganda", "+256", "🇺🇬"),
    CountryInfo("Ukraine", "+380", "🇺🇦"),
    CountryInfo("UAE", "+971", "🇦🇪"),
    CountryInfo("UK", "+44", "🇬🇧"),
    CountryInfo("USA", "+1", "🇺🇸"),
    CountryInfo("Uruguay", "+598", "🇺🇾"),
    CountryInfo("Uzbekistan", "+998", "🇺🇿"),
    CountryInfo("Vanuatu", "+678", "🇻🇺"),
    CountryInfo("Venezuela", "+58", "🇻🇪"),
    CountryInfo("Vietnam", "+84", "🇻🇳"),
    CountryInfo("Yemen", "+967", "🇾🇪"),
    CountryInfo("Zambia", "+260", "🇿🇲"),
    CountryInfo("Zimbabwe", "+263", "🇿🇼")
)
